# Generated by Django 3.1.1 on 2020-09-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_celular_1', models.CharField(choices=[('CP', 'Celular Personal'), ('CL', 'Celular Laboral'), ('LP', 'Linea Personal'), ('LL', 'Linea Laboral')], default='CP', max_length=20)),
                ('telefono1', models.CharField(max_length=60)),
                ('tipo_celular_2', models.CharField(choices=[('CP', 'Celular Personal'), ('CL', 'Celular Laboral'), ('LP', 'Linea Personal'), ('LL', 'Linea Laboral')], default='CP', max_length=20)),
                ('telefono2', models.CharField(max_length=60)),
                ('especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='obra_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=120)),
                ('cuit', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_turno', models.DateTimeField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('asistio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('tipo_celular_1', models.CharField(choices=[('CP', 'Celular Personal'), ('CL', 'Celular Laboral'), ('LP', 'Linea Personal'), ('LL', 'Linea Laboral')], default='CP', max_length=20)),
                ('telefono1', models.CharField(max_length=50)),
                ('tipo_celular_2', models.CharField(choices=[('CP', 'Celular Personal'), ('CL', 'Celular Laboral'), ('LP', 'Linea Personal'), ('LL', 'Linea Laboral')], default='CP', max_length=20)),
                ('telefono2', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=250)),
                ('medicos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.medicos')),
                ('obra_social_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.obra_social')),
            ],
        ),
    ]
