# Generated by Django 3.1.1 on 2020-09-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='medicos',
            name='telefono1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='telefono2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='turno',
            name='asignado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario'),
            preserve_default=False,
        ),
    ]
