# Generated by Django 3.1.1 on 2020-09-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200924_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='numero_de_afiliado',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='asignado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario'),
        ),
    ]
