# Generated by Django 3.1.1 on 2020-09-30 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200930_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_turno',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 1, 1, 1), null=True),
        ),
    ]
